#!/bin/sh
for i in `seq 0 3`; do
   echo 1 >  /sys/devices//system/cpu/cpu$i/cpuidle/state1/disable
done
jailhouse enable /usr/share/jailhouse/cells/rtbox-root.cell
while [ ! -d /sys/devices/jailhouse/cells/1 ]; do
   jailhouse cell create /usr/share/jailhouse/cells/rtbox-inmate.cell
done

